version: '3.9'

services:
  app:
    image: python:3.10-slim
    command: ["python", "/app/main.py"]
    volumes:
      - azurefileshare:/app/data
    working_dir: /app
    ports:
      - "5000:5000"

volumes:
  azurefileshare:
    driver: local
    driver_opts:
      type: cifs
      device: "//${AZURE_STORAGE_ACCOUNT}.file.core.windows.net/${AZURE_FILE_SHARE}"
      o: username=${AZURE_STORAGE_ACCOUNT},password=${AZURE_STORAGE_KEY},file_mode=0777,dir_mode=0777

